apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ulxy4rpcp-python 
  janus-idp.io/tekton: ulxy4rpcp-python
  backstage.io/kubernetes-id: ulxy4rpcp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ulxy4rpcp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml